name: Build and Push Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate semantic date version
        id: version
        run: |
          DATE=$(date +'%Y.%m.%d')
          # Count existing releases for today
          COUNT=$(gh release list --limit 100 --json tagName -q ".[] | select(.tagName | startswith(\"$DATE\"))" | wc -l)
          COUNT=$((COUNT+1))
          VERSION="$DATE.$COUNT"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/jobtrackerrazor:latest
            ghcr.io/${{ github.repository_owner }}/jobtrackerrazor:${{ env.VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          draft: false
          prerelease: false
          files: |
            JobsApp.xml
            compose.yaml
          body: |
            ## Docker Images
            - ghcr.io/${{ github.repository_owner }}/jobtrackerrazor:latest
            - ghcr.io/${{ github.repository_owner }}/jobtrackerrazor:${{ env.VERSION }}
            ## Quick Start
            ### Using Docker Compose
            Download `compose.yaml` and run:
            ```bash
            docker-compose up -d
            ```

            ### Using Unraid
            Download `JobApp.xml` template and add to your Unraid server in `/boot/config/plugins/dockerMan/templates-user/`
            This should work as of Unraid 7.1.2

            ## What's Changed
            See commit history for details.